name: Download dataset

on:
  push:
    branches:
      - nk/add-post-training-script-to-compute-csa
  # release:
  #   types: [published]

jobs:
  run_dataset_download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge

      - name: Create and activate Conda environment
        run: |
          conda env create -f scripts/environment.yml  # Create environment from the file
          source $(conda info --base)/etc/profile.d/conda.sh  # Enable conda command
          conda activate myenv  # Activate the environment
      
      # - name: Install dependencies
      #   run: |
      #     conda install -y git-annex
      #     pip install pyyaml
      #     python -c "import yaml; print('PyYAML is installed correctly!')"

      - name: Ensure git-annex is accessible via git
        run: |
          echo "$(conda info --base)/bin" >> $GITHUB_PATH
          export PATH="$(conda info --base)/bin:$PATH"
          which git-annex
          git-annex version

      - name: Configure Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Run dataset setup script
        shell: bash -l {0}  # Ensures the Conda environment is properly loaded
        run: |
            chmod +x scripts/compute_morphometrics_spine_generic.sh
            source scripts/compute_morphometrics_spine_generic.sh

      # - name: Run model script
      #   run: ./scripts/run_model.sh
